# Specify docker as a dependency
# Build test version of React project
# Run tests
# Build prod version of ALL projects
# Push all to dockerhub
# Tell EBS to update
sudo : required
language: generic 
services: 
    -docker

before_install:
    - docker build -t tomsou/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true tomsou/react-test npm test
    # - docker run for the other apps, if tests exist for them
after success:
    - docker build -t tomsou/multi-client ./client
    - docker build -t tomsou/multi-nginx ./nginx
    - docker build -t tomsou/multi-worker ./worker
    - docker build -t tomsou/multi-server ./server
    # push to Dockerhub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push tomsou/multi-client
    - docker push tomsou/multi-nginx
    - docker push tomsou/multi-worker
    - docker push tomsou/multi-server



deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-240214745020
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY